/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Usage: ./gradlew run --args=\"<day>\"");
            return;
        }
        
        String day = args[0];
        System.out.println("Running Day " + day);
        // TODO: Call Day01.solve(), Day02.solve(), etc. based on input
    }
}
