/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;

import org.example.day01.Day01;
import org.example.utils.Utils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        if (args.length == 0) {
            System.out.println("Usage: ./gradlew run --args=\"<day>\"");
            return;
        }
        
        String day = args[0];
        String part = args[1];
        System.out.println("Running Day " + day + " Part " + part);
        if (part.equals("1")) {
            List<String> instructions = Utils.readResource("inputs/day1.txt");
            int result = Day01.runPartOne(instructions, 50);
            System.out.println("Result: " + result);
        // } else if (part.equals("2")) {
        //     Day01.runPartTwo(instructions);
        }
        // TODO: Call Day01.solve(), Day02.solve(), etc. based on input
    }
}
